export const LOAD_GROUP_SUCCESS = 'LOAD_GROUP_SUCCESS';
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';

export const LOAD_PERSON_SUCCESS = 'LOAD_PERSON_SUCCESS';
export const UPDATE_PERSON_SUCCESS = 'UPDATE_PERSON_SUCCESS';
export const CREATE_PERSON_SUCCESS = 'CREATE_PERSON_SUCCESS';
export const DELETE_PERSON_SUCCESS = 'DELETE_PERSON_SUCCESS';