export const LOAD_RULE_SUCCESS = 'main/LOAD_RULE_SUCCESS';
export const UPDATE_ENTITY_SUCCESS = 'main/UPDATE_RULE_SUCCESS';
export const CREATE_CUSTOMER_SUCCESS = 'main/CREATE_CUSTOMER_SUCCESS';
export const CREATE_RULE_SUCCESS = 'main/CREATE_RULE_SUCCESS';
export const DELETE_RULE_SUCCESS = 'main/DELETE_RULE_SUCCESS';